#!/bin/bash

# get parameters
read -p "# container image registry 로그인 username: " username
read -p "# container image registry 로그인 password: " password
read -p "# kubernetes context name(현재 context는 .): " context
read -p "# 배포대상 프로파일(dev,prod중 선택): " profile
read -p "# base directory(현재 directory는 .): " basedir
if [ "${profile}" == "dev" ] || [ "${profile}" == "prod" ]; then
	echo "#### Copy below commands #####"
	echo "# Build & Deploy "
	echo "${basedir}/cicd/cmd/run-all ${username} ${password} ${context} ${profile} ${basedir}"
	echo "# Build only"
	echo "${basedir}/cicd/cmd/build-image ${username} ${password} ${basedir}"
	echo "# Deploy only"
	echo "${basedir}/cicd/cmd/deploy ${context} ${profile} ${basedir}"
	echo "# Clear all"
	echo "${basedir}/cicd/cmd/clear-all ${basedir}"
	echo ""
	read -n 1 -p "# Do you want to continue?(y/n) ... " cont
	echo ""
	if [ "${cont}" != "y" ]; then exit 0; fi

else
	echo "배포대상 profile은 dev 또는 prod여야 합니다."
	exit 0
fi

shell=run-all
# download shell if it's not exists
cmdpath=${basedir}/cicd/cmd

which ${cmdpath}/${shell} 2> /dev/null
if [ $? -eq 1 ]; then
	mkdir -p ${cmdpath} 2> /dev/null
	wget -O ${cmdpath}/${shell} https://happycloudpak.github.io/cicd-template/cmd/${shell}
	if [ $? -eq 1 ]; then
		echo "CAN'T download ${cmdpath}/${shell}"
		exit 1
	fi
	echo "Download completed => ${cmdpath}/${shell}"
	chmod +x ${cmdpath}/${shell}
fi

${cmdpath}/${shell} ${username} ${password} ${context} ${profile} ${basedir}