#!/bin/bash

# get parameters
filepath=$1

# set variables from config.properties

while read line
do
  x=$(echo $line | grep "#")
  if [ $? -eq 1 ]; then
    y=$(echo $line | grep "=")
    if [ $? -eq 0 ]; then
        key=$(echo $line | cut -d "=" -f1 | tr -d " " | sed "s@\.@_@g")
        val=$(echo $line | cut -d "=" -f2)
        echo "${key}=${val}"
        #export ${key}=${val}
    fi
  fi 
done < ${filepath} 

exit 0